---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# The **messaging** Package

The goal of **messaging** is to provides a toolset for creating and issuing nicely-formatted text within R diagnostic messages and those messages given during warnings and errors. The formatting of the messages can be customized using templating features. Issues with singular and plural forms can be handled through specialized syntax.

### Installation of the package

**messaging** is used in an R environment. If you don't have an R installation, it can be obtained from the [**Comprehensive R Archive Network (CRAN)**](https://cran.r-project.org/).

You can install the development version of **messaging** from **GitHub** using the **devtools** package.

```r
devtools::install_github("rich-iannone/messaging")
```

If you encounter a bug, have usage questions, or want to share ideas to make this package better, feel free to file an [issue](https://github.com/rich-iannone/messaging/issues).

## Code of Conduct

[Contributor Code of Conduct](https://github.com/rich-iannone/messaging/blob/master/CODE_OF_CONDUCT.md). By participating in this project you agree to abide by its terms.

## License

MIT &copy; Richard Iannone

